# head
menu:
  カタログ: /archives

rss: /atom.xml
favicon: /favicon.png

# main
date_format: 'MMMM D, YYYY'
excerpt_link: READ MORE
comment_link: 0 COMMENTS

google_analytics: UA-73840162-1
disqus_shortname: ochukai
